config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :products
  resources :order_items
  resources :orders, only: [:update]

  resource :cart, only: [:show] do
    collection do 
      get 'checkout'
    end
  end 
  root to: 'home#index'

  # Error pages
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  # Routing for static pages in /views/pages/*
  get "/:page" => "pages#show"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :confirmable, :database_authenticatable, :lockable,
         :registerable, :recoverable, :rememberable,
         :timeoutable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/cook.rb
class Cook < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :confirmable, :database_authenticatable, :lockable,
         :registerable, :recoverable, :rememberable,
         :timeoutable, :trackable, :validatable

  has_many :products
  has_many :subscriptions
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {
    awaiting_payment: 0,
    open: 1,
    accepted: 2,
    rejected: 3,
    completed: 4,
    cancelled: 5,
    refunded: 6
  }
  has_many :order_items
  belongs_to :profile, required: false
  before_save :update_total

  def add_product(item_params)
    item = self.order_items.find_by(product_id: item_params[:product_id])

    if item
      item.quantity += item_params[:quantity].to_i
      item.save!
    else
      new_item = self.order_items.new(item_params)
    end
  end

  def cancel
    self.order.update_attribute(status:"cancelled")
  end



  def calculate_total
    self.order_items.each { |x| puts x.product.inspect }
    self.order_items.collect { |item| item.product.price * item.quantity }.sum
  end

  private

  def update_total
    self.total_price = calculate_total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :cook, class_name: 'Profile'
  has_many :order_items

  def owner_of? (profile)
    cook_id == profile.id
  end

  def self.owner_products (profile)
    return Product.where(cook_id: profile.id).ids
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :products, foreign_key: :cook_id, dependent: :destroy
  has_many :orders
  has_one :user

  enum role: [:user, :cook, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/models/provider.rb
class Provider < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :confirmable, :database_authenticatable, :lockable,
         :registerable, :recoverable, :rememberable,
         :timeoutable, :trackable, :validatable

  has_many :products
  has_many :subscriptions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :omniauthable
  devise :confirmable, :database_authenticatable, :lockable,
         :registerable, :recoverable, :rememberable,
         :timeoutable, :trackable, :validatable

  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile

  after_initialize :init_profile

  def init_profile
    if new_record?
      build_profile
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  helper_method :current_order

  def current_order
    if session[:order_id]
      return Order.find(session[:order_id])
    else
      return Order.new
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @order_items = current_order.order_items
    @total_price = current_order.total_price
  end

  def checkout
    current_order.update_attributes( status: "open", profile: current_user.profile)
    session[:order_id] = nil
    redirect_to cart_path
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render(:status => 404)
  end

  def internal_server_error
    render(:status => 500)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user.present?
      render "index" and return
    end

    profile = current_user.profile

    if profile.cook?
      @products = Product.where(cook_id: current_user.id)
      @cook_orders = Order.joins(:order_items).where( order_items: {product_id: Product.owner_products(profile)})
    end

    @orders = Order.where(profile_id: current_user.profile)

    render "index_#{current_user.profile.role}"
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController

  def create
    @order = current_order
    @item = @order.add_product(item_params)
    if @order.save
      session[:order_id] = @order.id
      redirect_to products_path
    else
      flash.now[:error] = "Something is wrong"
      redirect_to products_path
    end
  end

  def destroy
    @order = current_order
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to cart_path
  end

  private

  def item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    begin
      render template: "pages/#{params[:page]}"
    rescue ActionView::MissingTemplate => error
      raise ActionController::RoutingError.new('Not Found')
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
    @order_item = current_order.order_items.new
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /products/1
  def update
    authorize @product

    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:name, :category_id, :price, :short_description, :description).merge(cook_id: current_user.id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) {|u|
        u.permit(:email, :password, :password_confirmation, profile_attributes: [:first_name, :infix, :last_name])}
    end
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/carts/show.html.haml
%h1 Shopping cart
.row
  - if @order_items.any?
    %table.bordered#cart_products
      / %thead
      /   %tr
      /     %th
      /     %th Name
      /     %th Item Name
      /     %th Item Price
      %tbody
      - @order_items.each do |item|
        %tr
          %td=image_tag("food.jpg", :alt => "Product image", class: "cart_product_image")
          %td= item.product.name
          %td Unit Price: #{number_to_currency item.product.price}
          %td Quantity: #{item.quantity}
          %td Total Price: #{number_to_currency (item.product.price * item.quantity)}
          %td= link_to 'Show', item.product
          %td= link_to 'Delete', order_item_path(item), method: :delete, data: { confirm: 'Are you sure?' }

    %table#cart_total
      %tbody
        %tr
          %td Aantal
          %td= number_to_currency(@total_price)
        %tr
          %td Shipping costs
          %td None
        %tr#total
          %td Total
          %td= number_to_currency(@total_price)

    =link_to 'Checkout', checkout_cart_path

  - else
    .col.s12.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          Your shopping cart is empty.

%br/

app/views/home/index.html.haml
- content_for(:page, 'home')

.page
  .container
    .panel
      Hello world!
      This is a blank page for people who haven't logged in!

app/views/home/index_admin.html.haml
%h1 Dashboard Admin
%p
%br/

app/views/home/index_cook.html.haml
%h1 Dashboard Cook

.row
  - @products.each do |product|
    .col.s12.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          %span.card-title
            =product.name
          %p
            I'm a product! My category is
            = product.category.name
        .card-action
          = link_to 'Show', product
          = link_to 'Edit', edit_product_path(product)
          = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
%br/

.row
  - @cook_orders.each do |order|
    .col.s12.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          .card-title
            Status: #{order.status}
            %br
            Total price: #{order.total_price}
          .card-content
            - order.order_items.each do |order_item|
              #{order_item.product.name} (#{order_item.quantity}x)
        .card-action
          = link_to 'Accept', order_path(order, order: { status: 'accepted'}), method: :put
          = link_to 'Reject', order_path(order, order: { status: 'rejected'}), method: :put

= link_to 'New product', new_product_path, class: "waves-effect waves-light btn"

app/views/home/index_user.html.haml
%h1 Dashboard User
%p
%br/

.row
  - @orders.each do |order|
    .col.s12.m6
      .card.blue-grey.darken-1
        .card-content.white-text
          .card-title
            Status: #{order.status}
            %br
            Total price: #{order.total_price}
          .card-content
            - order.order_items.each do |order_item|
              #{order_item.product.name} (#{order_item.quantity}x)
        .card-action
          = link_to 'Cancel', order_path(order, order: { status: 'cancelled'}), method: :put

app/views/products/_form.html.haml
= form_for(product) do |f|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    = f.text_field :name, required: true, placeholder: "Name of the product"
  .field
    = f.label :category_id
    = f.collection_select(:category_id, Category.all, :id, :name, required: true, include_blank: "Please select a category")
  .field
    = f.label :price
    = f.number_field :price, required: true, placeholder: 0
  .field
    = f.label :short_description
    = f.text_field :short_description, required: true, placeholder: "This is a short line telling my customer what the product is about!"
  .field
    = f.label :description
    = f.text_area :description, class: "materialize-textarea", required: true, placeholder: "Larger text telling the customer what this product is about!"
  .actions
    = f.submit

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product
%p
= link_to 'Show', @product, class: "waves-effect waves-light btn"
= link_to 'Back', products_path, class: "waves-effect waves-light btn"

app/views/products/index.html.haml
%h1 Products
.flex-products
  - @products.each do |product|
    .card.blue-grey.darken-1.flex-product
      = link_to product do
        .card-image
          =image_tag("food.jpg", :alt => "Product image")
        .card-content.white-text
          %span.card-title.orange-text
            =product.name
          =product.short_description
        .card-action.white-text
          =product.category.name
          .price.orange-text= "€#{product.price}"

app/views/products/new.html.haml
%h1 New Product
= render 'form', product: @product
%p
= link_to 'Back', products_path, class: "waves-effect waves-light btn"

app/views/products/show.html.haml
.row
  .col.s12.m12
    .card.blue-grey.darken-1
      .card-image
        =image_tag("food.jpg", :alt => "Product image")
      .card-content.white-text
        %span.card-title
          = @product.name
          .price.orange-text= "€#{@product.price}"
        %p
          = @product.description
      .card-action
        = link_to 'Back', products_path
        - if policy(@product).update?
          = link_to "Edit", edit_product_path(@product)
        - if policy(@product).destroy?
          = link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure?' }
        - if policy(@product).buy?
          = form_for(@order_item) do |f|
            = f.hidden_field :product_id, value: @product.id
            = f.hidden_field :quantity, value: 1
            = f.submit 'Add to cart', class: 'btn waves-effect'
            = f.select :quantity, ((1..4).map {|i| [i,i] })